repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key       # New: Security
        exclude: ^teleswitch/config/tls/  # This tells it to skip that folder
      - id: check-added-large-files  # New: Performance

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: docker-compose-validate
        name: docker compose validate
        entry: docker compose config
        language: system
        files: ^docker-compose\.ya?ml$
        pass_filenames: false

#  - name: Install Docker Compose
#        run: sudo apt-get update && sudo apt-get install docker-compose-v2
